<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-NGKP0VFT" tests="10" failures="1" timestamp="11 Aug 2019 07:20:08 GMT" time="2.225" errors="0">
  <testcase name="testAddUser" time="0.645" classname="UserAddTest"/>
  <testcase name="testDismissParam" time="0.103" classname="UserAddTest"/>
  <testcase name="testAddDuplicateUser" time="0.046" classname="UserAddTest"/>
  <testcase name="testDismissParam" time="0.083" classname="UserEditTest"/>
  <testcase name="testEditMember1" time="0.151" classname="UserEditTest"/>
  <testcase name="testEditMember1" time="0.157" classname="UserEditTest"/>
  <testcase name="testSpeChar" time="0.125" classname="UserEditTest"/>
  <testcase name="testSearchByuname" time="0.073" classname="UserListTest"/>
  <testcase name="testDeleteUser" time="0.055" classname="UserDeleteTest"/>
  <testcase name="testDeleteNotExistUser" time="0.04" classname="UserDeleteTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
	at UserDeleteTest.testDeleteNotExistUser(UserDeleteTest.java:53)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteNotExistUser -->
</testsuite>
